<?xml version="1.0"?>
<robot name="limo_four_diff" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find limo_description)/urdf/limo_xacro.xacro" />

  <!-- Vars -->
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="base_x_size" value="0.13" />
  <xacro:property name="base_y_size" value="0.12" />
  <xacro:property name="base_z_size" value="0.10" />
  <xacro:property name="wheelbase" value="0.2"/>
  <xacro:property name="track" value="0.13"/>
  <xacro:property name="wheel_vertical_offset" value="-0.105" />
  <xacro:property name="wheel_length" value="0.045" />
  <xacro:property name="wheel_radius" value="0.045" />

  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
  </joint>

  <!-- Base -->
  <link name="base_link">
    <!-- 단일 질량/관성 블록 -->
    <inertial>
      <origin xyz="0 0 -0.05" rpy="0 0 0"/>
      <mass value="10.0"/>
      <inertia ixx="0.0203333333" ixy="0" ixz="0"
               iyy="0.0224166667" iyz="0"
               izz="0.0260833333"/>
    </inertial>

    <visual>
      <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
      <geometry>
        <mesh filename="file://$(find limo_description)/meshes/limo_base.dae" scale="1 1 1"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
  </link>

  <!-- Sensors -->
  <xacro:limo_laser parent_prefix="base_link" frame_prefix="laser">
    <origin xyz="0.103 0 -0.034" rpy="0 0 0"/>
  </xacro:limo_laser>
  <xacro:limo_depth_camera parent_prefix="base_link" frame_prefix="depth_camera">
    <origin xyz="0.084 0 0.3" rpy="0 0 0"/>
  </xacro:limo_depth_camera>
  <xacro:limo_imu parent_prefix="base_link" frame_prefix="imu">
    <origin xyz="0.0 0 -0.1" rpy="0 0 0"/>
  </xacro:limo_imu>

  <!-- Wheels -->
  <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_left"  reflect="1">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:limo_wheel>
  <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_right" reflect="-1">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
  </xacro:limo_wheel>
  <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_left"   reflect="1">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:limo_wheel>
  <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_right"  reflect="-1">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
  </xacro:limo_wheel>

  <!-- Gazebo: IMU -->
  <gazebo reference="imu_link">
    <gravity>true</gravity>
    <sensor name="twr_imu" type="imu">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>100</update_rate>
      <imu>
        <orientation>
          <x><noise type="gaussian"><mean>0.0</mean><stddev>2e-3</stddev></noise></x>
          <y><noise type="gaussian"><mean>0.0</mean><stddev>2e-3</stddev></noise></y>
          <z><noise type="gaussian"><mean>0.0</mean><stddev>2e-3</stddev></noise></z>
        </orientation>
      </imu>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <frame_name>imu_link</frame_name>
        <ros><namespace>/imu</namespace><remapping>~/out:=data</remapping></ros>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Gazebo: Laser -->
  <gazebo reference="laser_link">
    <sensor name="laser" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>20</update_rate>
      <ray>
        <scan><horizontal><samples>720</samples><resolution>1.0</resolution>
          <min_angle>-3.14</min_angle><max_angle>3.14</max_angle>
        </horizontal></scan>
        <range><min>0.3</min><max>15.0</max><resolution>0.005</resolution></range>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros><remapping>~/out:=scan</remapping></ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Gazebo: Base friction -->
  <gazebo reference="base_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <slip1>0.05</slip1>
    <slip2>0.05</slip2>
    <kp>2.0e6</kp>
    <kd>5</kd>
    <maxVel>0.2</maxVel>
    <minDepth>0.002</minDepth>
    <selfCollide>false</selfCollide>
    <maxContacts>15</maxContacts>
  </gazebo>

  <!-- Gazebo: Wheel friction -->
  <gazebo reference="front_left_wheel">
    <mu1>3.0</mu1><mu2>2.5</mu2>
    <slip1>0.02</slip1><slip2>0.02</slip2>
    <kp>1.0e6</kp><kd>5</kd>
    <maxVel>0.2</maxVel><minDepth>0.002</minDepth>
  </gazebo>
  <gazebo reference="front_right_wheel">
    <mu1>3.0</mu1><mu2>2.5</mu2>
    <slip1>0.02</slip1><slip2>0.02</slip2>
    <kp>1.0e6</kp><kd>5</kd>
    <maxVel>0.2</maxVel><minDepth>0.002</minDepth>
  </gazebo>
  <gazebo reference="rear_left_wheel">
    <mu1>3.0</mu1><mu2>2.5</mu2>
    <slip1>0.02</slip1><slip2>0.02</slip2>
    <kp>1.0e6</kp><kd>5</kd>
    <maxVel>0.2</maxVel><minDepth>0.002</minDepth>
  </gazebo>
  <gazebo reference="rear_right_wheel">
    <mu1>3.0</mu1><mu2>2.5</mu2>
    <slip1>0.02</slip1><slip2>0.02</slip2>
    <kp>1.0e6</kp><kd>5</kd>
    <maxVel>0.2</maxVel><minDepth>0.002</minDepth>
  </gazebo>

  <!-- Gazebo: Diff drive plugin (조인트 이름 = 매크로 생성 그대로) -->
  <gazebo>
    <plugin name="four_diff_controller" filename="libgazebo_ros_diff_drive.so">
      <update_rate>50</update_rate>

      <!-- 왼쪽 바퀴 두 개 -->
      <left_joint>front_left_wheel</left_joint>
      <left_joint>rear_left_wheel</left_joint>

      <!-- 오른쪽 바퀴 두 개 -->
      <right_joint>front_right_wheel</right_joint>
      <right_joint>rear_right_wheel</right_joint>
      <num_wheel_pairs>2</num_wheel_pairs>
      <wheel_separation>${track}</wheel_separation>
      <wheel_diameter>0.09</wheel_diameter>
      <max_wheel_torque>8.0</max_wheel_torque>
      <max_wheel_acceleration>0.15</max_wheel_acceleration>

      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <robot_base_frame>base_footprint</robot_base_frame>
      <ros><remapping>odom:=/odometry</remapping></ros>
    </plugin>
  </gazebo>

</robot>
