<?xml version="1.0"?>
<robot name="limo_ackerman" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Args -->
  <xacro:arg name="robot_namespace" default="/limo"/>

  <!-- Common macros -->
  <xacro:include filename="$(find limo_description)/urdf/limo_xacro.xacro"/>
  <xacro:include filename="$(find limo_description)/urdf/limo_steering_hinge.xacro"/>

  <!-- ===== Vehicle parameters ===== -->
  <xacro:property name="M_PI" value="3.141592653589793"/>
  <xacro:property name="base_x_size" value="0.13"/>
  <xacro:property name="base_y_size" value="0.12"/>
  <xacro:property name="base_z_size" value="0.10"/>
  <xacro:property name="wheelbase" value="0.40"/>
  <xacro:property name="track" value="0.26"/>
  <xacro:property name="wheel_vertical_offset" value="-0.12"/>
  <xacro:property name="wheel_length" value="0.045"/>
  <xacro:property name="wheel_radius" value="0.045"/>

  <!-- ===== Base frames ===== -->
  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="10.0"/>
      <inertia ixx="0.0203333333" ixy="0" ixz="0" iyy="0.0224166667" iyz="0" izz="0.0260833333"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.15" rpy="0 0 1.57"/>
      <geometry>
        <mesh filename="package://limo_description/meshes/limo_base.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
  </link>

  <!-- ===== Front steering (Ackermann) ===== -->
  <xacro:limo_left_steering_hinge parent_prefix="base_link" wheel_prefix="left_steering_joint">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:limo_left_steering_hinge>

  <xacro:limo_right_steering_hinge parent_prefix="base_link" wheel_prefix="right_steering_joint">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0"/>
  </xacro:limo_right_steering_hinge>

  <!-- ===== Rear wheels ===== -->
  <link name="rear_left_wheel_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01055" ixy="0" ixz="0" iyy="0.00075" iyz="0" izz="0.01055"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://limo_description/meshes/limo_wheel.dae"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <joint name="rear_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel_link"/>
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="rear_right_wheel_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01055" ixy="0" ixz="0" iyy="0.00075" iyz="0" izz="0.01055"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://limo_description/meshes/limo_wheel.dae"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <joint name="rear_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel_link"/>
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
  </joint>

  <!-- Gazebo 플러그인 include -->
  <xacro:include filename="$(find limo_description)/urdf/limo_ackerman.gazebo"/>
</robot>
