amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: map.yaml

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: [GridBased]
    GridBased:
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.5

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: [FollowPath]
    FollowPath:
      plugin: nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: navigate_w_replanning_and_recovery.xml

behavior_server:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    plugin: nav2_waypoint_follower/WaypointFollower

recoveries_server:
  ros__parameters:
    use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.22
      plugins: [obstacle_layer, inflation_layer]
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 10.0
      height: 10.0
      resolution: 0.05
      robot_radius: 0.22
      plugins: [static_layer, obstacle_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer