controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    use_stamped_vel: false
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    front_steering: true
    front_wheels_names: ["left_steering_joint", "right_steering_joint"]
    rear_wheels_names:  ["rear_left_joint", "rear_right_joint"]
    wheelbase: 0.40
    front_wheel_track: 0.26
    rear_wheel_track:  0.26
    front_wheels_radius: 0.045
    rear_wheels_radius:  0.045
    position_feedback: false
    open_loop: false
    reference_timeout: 0.5
    velocity_rolling_window_size: 10
